stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: authentication:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: registry-docker.digitalplanet.com.tr:5000
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
