apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: 1-tetra
  labels:
    app: authentication
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: authentication
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports: 8080
        - containerPort: 80
      resources:
        limits:
          cpu: "150m"
          memory: "1024Mi"
        requests:
          cpu: "100m"
          memory: "512Mi"
