kind: Service
apiVersion: v1
metadata:
  name: authentication
spec:
  selector:
    app: authentication
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  labels:
    app: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: authentication
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
